name: Latest blog post workflow and snake generated

on:
  schedule:
      # every 12 hours
    - cron: '0 * * * *'

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  push: {branches: ["yamlnot", "main"]}
  
jobs: 

    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: deep-matter/blog-post-workflow@v1
              with: 
                max_post_count: "3"
                remove_duplicates: true
                feed_list: "https://medium.com/@younsess-elbrag"
      # Snake Animation
            - uses: Platane/snk@master
              id: snake-gif
        
              with:
                github_user_name: deep-matter
                svg_out_path: dist/github-contribution-grid-snake.svg
            - uses: crazy-max/ghaction-github-pages@v2.1.3
              with:
                target_branch: output
                build_dir: dist
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}